ALTER TABLE "UpsellOffer" ADD COLUMN "benefitsImageUrl" TEXT;
ALTER TABLE "UpsellOffer" ADD COLUMN "showThumbnails" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UpsellOffer" ADD COLUMN "showBenefitsSection" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UpsellOffer" ADD COLUMN "showComparisonSection" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UpsellOffer" ADD COLUMN "contentSpacing" TEXT NOT NULL DEFAULT 'COMFORTABLE';
ALTER TABLE "UpsellOffer" ADD COLUMN "headingSize" TEXT NOT NULL DEFAULT 'LARGE';
ALTER TABLE "UpsellOffer" ADD COLUMN "imageFit" TEXT NOT NULL DEFAULT 'CONTAIN';
ALTER TABLE "UpsellOffer" ADD COLUMN "benefitsImageFit" TEXT NOT NULL DEFAULT 'COVER';
