ALTER TABLE "UpsellOffer" ADD COLUMN "showHeadline" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UpsellOffer" ADD COLUMN "savingsLabel" TEXT NOT NULL DEFAULT 'POST-PURCHASE OFFER';
ALTER TABLE "UpsellOffer" ADD COLUMN "showSavingsLabel" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UpsellOffer" ADD COLUMN "showFooterNote" BOOLEAN NOT NULL DEFAULT true;
